In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
customers = pd.read_csv(r"../01_Raw_Data/crm_50000_customers_dirty_v3.csv")
orders = pd.read_csv(r"../01_Raw_Data/orders_300k_dirty.csv")
support = pd.read_csv(r"../01_Raw_Data/support_tickets_30000_dirty.csv")
products = pd.read_csv(r"../01_Raw_Data/product_catalog_dirty_30pct.csv")
clickstream = pd.read_csv(r"../01_Raw_Data/clickstream_500k_events.csv")

print("Customers:", customers.shape)
print("Orders:", orders.shape)
print("Support Tickets:", support.shape)
print("Products:", products.shape)
print("Clickstream:", clickstream.shape)

Customers: (50000, 14)
Orders: (300000, 8)
Support Tickets: (30000, 8)
Products: (500, 4)
Clickstream: (500000, 8)

In [3]:
customers_clean = customers.copy()
orders_clean = orders.copy()
support_clean = support.copy()
products_clean = products.copy()
clickstream_clean = clickstream.copy()

In [4]:
print(customers_clean.shape)
print(orders_clean.shape)
print(support_clean.shape)
print(products_clean.shape)
print(clickstream_clean.shape)

(50000, 14)
(300000, 8)
(30000, 8)
(500, 4)
(500000, 8)

In [5]:
duplicate_customer_ids = customers_clean[customers_clean["customer_id"].duplicated(keep=False)]

print("Row with duplicate customer ids: ", len(duplicate_customer_ids))

print("Unique duplicate customer ids: ", duplicate_customer_ids["customer_id"].nunique())

Row with duplicate customer ids:  3534
Unique duplicate customer ids:  1734

In [6]:
customers_clean[customers_clean["customer_id"].duplicated(keep=False)].sort_values("customer_id").head(20)

,customer_id,first_name,last_name,email,phone_number,gender,dob,signup_date,address,city,state,country,device_id(s),source
1393,005a7521-db6a-406e-b14e-97bf259f96fb,Alexandra,Ellison,alexandra.ellison003@yahoo.com,(543)768-3047x8198,M,2005-06-09,2018-04-29,427 Walton Canyon,Jamiechester,Arkansas,France,14edf41b-5067-45da-834f-7318116cc466,referral
5785,005a7521-db6a-406e-b14e-97bf259f96fb,Alexandra,Ellison,alexandra.ellison003@yahoo.com,(543)768-3047x8198,M,2005-06-09,2018-04-29,427 Walton Canyon,Jamiechester,Arkansas,France,14edf41b-5067-45da-834f-7318116cc466,referral
30391,00682ed4-54ac-434e-b800-a4dfa3775f10,Melissa,Peck,shared1349@hotmail.com,6610153591,M,2001-01-19,2024-11-20,893 Chavez Landing Suite 262,New Carrieville,Hawaii,Serbia,002db8ff-ed9f-48ed-ac1b-9f977421bc66,app
38030,00682ed4-54ac-434e-b800-a4dfa3775f10,Melissa,PECK,shared1349@hotmail.com,6610153591,M,2001-01-19,2024-11-20,893 Chavez Landing Suite 262,New Carrieville,Hawaii,Serbia,002db8ff-ed9f-48ed-ac1b-9f977421bc66,app
17061,0070c246-7754-46db-a55f-b14188840068,JOSEPH,sMITH,joseph.smith734@hotmail.com,001-740-556-0991,F,1996-05-10,2021-05-15,2067 Allen Ways,New Patricia,Louisiana,Palau,c33a812d-fb6d-485e-be77-fc0e1526afeb,web
39917,0070c246-7754-46db-a55f-b14188840068,Joseph,Smith,joseph.smith734@hotmail.com,001-740-556-0991,F,1996-05-10,2021-05-15,2067 Allen Ways,New Patricia,Louisiana,Palau,c33a812d-fb6d-485e-be77-fc0e1526afeb,web
43335,00b15609-c67f-4057-a23e-846120a5a078,John,Paul,john.paul309@yahoo.com,+1-045-245-5744x387,M,1960-01-19,2022-03-22,95225 Davis Passage,Orozcochester,South Carolina,Syrian Arab Republic,1f8da822-3fad-40c4-9c0a-2b9a8adb3325,referral
400,00b15609-c67f-4057-a23e-846120a5a078,John,Paul,john.paul309@yahoo.com,+1-045-245-5744x387,M,1960-01-19,2022-03-22,95225 Davis Passage,Orozcochester,South Carolina,Syrian Arab Republic,1f8da822-3fad-40c4-9c0a-2b9a8adb3325,referral
43939,00c929d1-753c-49a8-af28-eb3ffe0ad087,Tina,Frost,caitlin.richardson319@hotmail.com,(142)446-4128,M,1996-05-01,2016-11-01,531 Michael Fords Suite 310,Lake Michaelberg,Wyoming,Gabon,14c1d235-28f3-4376-ba5c-758f17d67c68,referral
34468,00c929d1-753c-49a8-af28-eb3ffe0ad087,tINA,Frost,caitlin.richardson319@hotmail.com,(142)446-4128,M,1996-05-01,2016-11-01,531 Michael Fords Suite 310,Lake Michaelberg,Wyoming,Gabon,14c1d235-28f3-4376-ba5c-758f17d67c68,referral
43836,00d5aa6f-3b76-40da-90a7-1526ae3211b3,Kelly,Bennett,shared1450@gmail.com,605.131.6162x349,F,1976-09-01,2021-12-05,7015 James Falls,Kristenport,Arizona,Oman,6b05d63b-4d11-4c6d-9e14-770f657c6a39,app
17609,00d5aa6f-3b76-40da-90a7-1526ae3211b3,Kelly,Bennett,shared1450@gmail.com,605.131.6162x349,F,1976-09-01,2021-12-05,7015 James Falls,Kristenport,Arizona,Oman,6b05d63b-4d11-4c6d-9e14-770f657c6a39,app
36079,00d9d551-d21c-4355-a3a6-6a76180194c8,Brad,Jones,brad.jones644@gmail.com,+1-710-203-1409x51948,F,1960-04-19,2020-04-16,302 Taylor Groves Suite 333,South Stephanie,South Carolina,New Zealand,c133b493-008d-4ec2-a934-b13782fbb1e2,app
27020,00d9d551-d21c-4355-a3a6-6a76180194c8,Brad,Jones,brad.jones644@gmail.com,+1-710-203-1409x51948,F,1960-04-19,2020-04-16,302 Taylor Groves Suite 333,South Stephanie,South Carolina,New Zealand,c133b493-008d-4ec2-a934-b13782fbb1e2,app
47769,011ecd43-e9f7-429c-b873-8a4f1ae4b96b,Mary,Rhodes,mary.rhodes599@yahoo.com,217-294-1398,F,2002-07-04,2018-05-06,2479 Robert Drive Suite 425,New Rodneyshire,Missouri,Nicaragua,3aab6405-b9dd-4e9d-b5f7-b50bda04d256,referral
41230,011ecd43-e9f7-429c-b873-8a4f1ae4b96b,Mary,Rhodes,mary.rhodes599@yahoo.com,217-294-1398,F,2002-07-04,2018-05-06,2479 Robert Drive Suite 425,New Rodneyshire,Missouri,Nicaragua,3aab6405-b9dd-4e9d-b5f7-b50bda04d256,referral
6339,0129287c-66ac-4751-9d43-e8521e1c37e7,Kelsey,Warner,kelsey.warner803@gmail.com,(252)532-5308x9668,M,1988-01-25,2015-02-15,89823 Bush Points Apt. 351,Cassandramouth,Delaware,Faroe Islands,7af9cdc0-20f8-4b2b-8647-89d362ea1707,web
28058,0129287c-66ac-4751-9d43-e8521e1c37e7,Kelsey,Warner,kelsey.warner803@gmail.com,(252)532-5308x9668,M,1988-01-25,2015-02-15,89823 Bush Points Apt. 351,Cassandramouth,Delaware,Faroe Islands,7af9cdc0-20f8-4b2b-8647-89d362ea1707,web
32696,0167fd2f-c24d-4f99-a133-6678590ae380,Mic2hael,VALDEZ,michael.valdez657@gmail.com,0989040312,F,1963-02-26,2018-12-06,2137 Myers Cliffs,Bakerland,Oregon,Angola,530107b6-b7f9-4da1-a3c8-bb4dcf9e5cb5,app
28123,0167fd2f-c24d-4f99-a133-6678590ae380,Michael,Valdez,michael.valdez657@gmail.com,0989040312,F,1963-02-26,2018-12-06,2137 Myers Cliffs,Bakerland,Oregon,Angola,530107b6-b7f9-4da1-a3c8-bb4dcf9e5cb5,app

In [7]:
customers_clean = customers.drop_duplicates()
print("Rows after removing exact duplicates:", len(customers_clean))

Rows after removing exact duplicates: 48979

In [8]:
duplicate_customer_ids = customers_clean[customers_clean["customer_id"].duplicated(keep=False)]

print("Row with duplicate customer ids: ", len(duplicate_customer_ids))

print("Unique duplicate customer ids: ", duplicate_customer_ids["customer_id"].nunique())

Row with duplicate customer ids:  1547
Unique duplicate customer ids:  768

In [9]:
id_counts = customers_clean["customer_id"].value_counts()

duplicate_ids = id_counts[id_counts > 1].index

customers_clean[customers_clean["customer_id"].isin(duplicate_ids)].sort_values("customer_id").head(20)

,customer_id,first_name,last_name,email,phone_number,gender,dob,signup_date,address,city,state,country,device_id(s),source
38030,00682ed4-54ac-434e-b800-a4dfa3775f10,Melissa,PECK,shared1349@hotmail.com,6610153591,M,2001-01-19,2024-11-20,893 Chavez Landing Suite 262,New Carrieville,Hawaii,Serbia,002db8ff-ed9f-48ed-ac1b-9f977421bc66,app
30391,00682ed4-54ac-434e-b800-a4dfa3775f10,Melissa,Peck,shared1349@hotmail.com,6610153591,M,2001-01-19,2024-11-20,893 Chavez Landing Suite 262,New Carrieville,Hawaii,Serbia,002db8ff-ed9f-48ed-ac1b-9f977421bc66,app
17061,0070c246-7754-46db-a55f-b14188840068,JOSEPH,sMITH,joseph.smith734@hotmail.com,001-740-556-0991,F,1996-05-10,2021-05-15,2067 Allen Ways,New Patricia,Louisiana,Palau,c33a812d-fb6d-485e-be77-fc0e1526afeb,web
39917,0070c246-7754-46db-a55f-b14188840068,Joseph,Smith,joseph.smith734@hotmail.com,001-740-556-0991,F,1996-05-10,2021-05-15,2067 Allen Ways,New Patricia,Louisiana,Palau,c33a812d-fb6d-485e-be77-fc0e1526afeb,web
34468,00c929d1-753c-49a8-af28-eb3ffe0ad087,tINA,Frost,caitlin.richardson319@hotmail.com,(142)446-4128,M,1996-05-01,2016-11-01,531 Michael Fords Suite 310,Lake Michaelberg,Wyoming,Gabon,14c1d235-28f3-4376-ba5c-758f17d67c68,referral
43939,00c929d1-753c-49a8-af28-eb3ffe0ad087,Tina,Frost,caitlin.richardson319@hotmail.com,(142)446-4128,M,1996-05-01,2016-11-01,531 Michael Fords Suite 310,Lake Michaelberg,Wyoming,Gabon,14c1d235-28f3-4376-ba5c-758f17d67c68,referral
28123,0167fd2f-c24d-4f99-a133-6678590ae380,Michael,Valdez,michael.valdez657@gmail.com,0989040312,F,1963-02-26,2018-12-06,2137 Myers Cliffs,Bakerland,Oregon,Angola,530107b6-b7f9-4da1-a3c8-bb4dcf9e5cb5,app
32696,0167fd2f-c24d-4f99-a133-6678590ae380,Mic2hael,VALDEZ,michael.valdez657@gmail.com,0989040312,F,1963-02-26,2018-12-06,2137 Myers Cliffs,Bakerland,Oregon,Angola,530107b6-b7f9-4da1-a3c8-bb4dcf9e5cb5,app
25598,01695a54-eb34-4506-873d-669cc875b8d0,Sean,Cook2e,sean.cooke027@yahoo.com,+1-764-716-2672,F,1959-12-03,2021-10-26,8290 Cynthia Fords Apt. 413,North Brenthaven,California,Lao People's Democratic Republic,3bbbfba2-0f31-40bc-b543-f2eabff95598,referral
26181,01695a54-eb34-4506-873d-669cc875b8d0,Sean,Cooke,sean.cooke027@yahoo.com,+1-764-716-2672,F,1959-12-03,2021-10-26,8290 Cynthia Fords Apt. 413,North Brenthaven,California,Lao People's Democratic Republic,3bbbfba2-0f31-40bc-b543-f2eabff95598,referral
28016,01c49ac0-9207-4a30-b5c2-87f76b5ee503,AAnnttonio,Ward,antonio.ward636@hotmail.com,001-320-679-0687x6831,F,2001-10-17,2022-08-17,32755 Anna Street Suite 527,West Aaron,Utah,Guam,3783afb1-ce5b-4796-b3c3-77ca6c42ff0f,web
5745,01c49ac0-9207-4a30-b5c2-87f76b5ee503,Antonio,Ward,antonio.ward636@hotmail.com,001-320-679-0687x6831,F,2001-10-17,2022-08-17,32755 Anna Street Suite 527,West Aaron,Utah,Guam,3783afb1-ce5b-4796-b3c3-77ca6c42ff0f,web
47043,02114cd2-1da6-42fe-b8c6-04e7d9922b53,Ale0x,Taylor@,alex.taylor701@hotmail.com,367-136-4335x7729,F,1975-10-08,2024-03-27,306 Sandoval Wells,Port Tiffany,Louisiana,South Africa,fa3dfd20-5a0e-41b4-94c8-fb302165c8e5,referral
3202,02114cd2-1da6-42fe-b8c6-04e7d9922b53,Alex,Taylor,alex.taylor701@hotmail.com,367-136-4335x7729,F,1975-10-08,2024-03-27,306 Sandoval Wells,Port Tiffany,Louisiana,South Africa,fa3dfd20-5a0e-41b4-94c8-fb302165c8e5,referral
4130,0285e90e-e420-4e22-a3fc-a9c4db5a87b1,Ronald,Lewis,shawn.cooper146@hotmail.com,163.817.3709x7749,O,1976-08-28,2016-05-27,841 Williams Villages Suite 128,Tinashire,Georgia,Estonia,e83114ea-d2dc-45e5-b674-2bf28f49446b,referral
49723,0285e90e-e420-4e22-a3fc-a9c4db5a87b1,Ronald,LEWIS,shawn.cooper146@hotmail.com,163.817.3709x7749,O,1976-08-28,2016-05-27,841 Williams Villages Suite 128,Tinashire,Georgia,Estonia,e83114ea-d2dc-45e5-b674-2bf28f49446b,referral
28279,0296267f-4157-4af2-a940-259a366d0b29,Amanda!,Wats4on,amanda.watson780@yahoo.com,001-401-287-6503x160,F,1978-06-17,2014-07-29,10292 Amy Walks Apt. 558,Troybury,Kentucky,Algeria,38e0b85f-d8f6-4d5e-acea-ea2bf940a357,web
35884,0296267f-4157-4af2-a940-259a366d0b29,amanda,Watson!,amanda.watson780@yahoo.com,001-401-287-6503x160,F,1978-06-17,2014-07-29,10292 Amy Walks Apt. 558,Troybury,Kentucky,Algeria,38e0b85f-d8f6-4d5e-acea-ea2bf940a357,web
14508,032f8a68-d58d-4393-9e51-cafd6015023d,Joshua,SSaannchez,NaN,(570)588-3871x41347,M,2001-10-10,2025-01-28,44550 Fox Lock,Elizabethfort,North Carolina,Ghana,37067444-0925-4e4f-af85-80e1f64b36ea,web
18422,032f8a68-d58d-4393-9e51-cafd6015023d,Joshua@,sANCHEZ,NaN,(570)588-3871x41347,M,2001-10-10,2025-01-28,44550 Fox Lock,Elizabethfort,North Carolina,Ghana,37067444-0925-4e4f-af85-80e1f64b36ea,web

In [10]:
text_columns = ["first_name", "last_name", "email", "phone_number", "gender", "address", "city", "state", "country", "device_id(s)", "source"]
for col  in text_columns:
    customers_clean[col] = customers_clean[col].str.strip().str.lower()
print(customers_clean.head())

C:\Users\user\AppData\Local\Temp\ipykernel_2836\2098906341.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  customers_clean[col] = customers_clean[col].str.strip().str.lower()

                            customer_id first_name last_name  \
0  0d244537-8164-4b84-bcf2-0e43766f3221      maria       day
1  66c5800b-ad5c-4fac-86df-16472d82f02d   kkeevvin     cantu
2  e7852eee-0a28-46dc-aa34-445a02530746     ronald    daniel
3  14f0e67d-e60e-4989-88cf-5be50d515a69  katherine     smith
4  1ce2f061-345c-4121-a4ba-32963cf9a15d    brandon    glover

                           email           phone_number gender         dob  \
0       maria.day697@hotmail.com       449.977.1729x282      m  1988-04-11
1       kevin.cantu968@gmail.com     501.347.4824x64633      m  1955-09-19
2     ronald.daniel138@yahoo.com  +1-268-822-6332x26814      m  1971-11-02
3   katherine.smith357@yahoo.com           864-894-1347      f  1955-03-25
4  brandon.glover804@hotmail.com           489.732.5436      m  1968-06-25

  signup_date                      address            city        state  \
0  2016-12-05           107 joseph station  padillaborough       oregon
1  2024-02-03    3577 anita knoll apt. 107       justinton     delaware
2  2016-04-12   3440 tammy views suite 698  new autumnland  mississippi
3  2019-06-21          98888 morales lakes        new jose    minnesota
4  2022-01-09  55037 denise crest apt. 565      port amber       oregon

      country                                       device_id(s)    source
0  micronesia  56f3a452-b3f5-488b-b90d-8cb2b3343c70;3ab7d21b-...  referral
1    portugal               cd83e240-0d50-4e67-b146-23deb6c49940  referral
2      uganda               369b8950-dfae-44ce-bbb4-d292f118be67       web
3     bahrain               3e83071f-53ed-4a05-9dfd-5ff2031443b5       web
4      latvia               751d4410-3d73-4f4c-b432-10a0213b925f  referral

In [11]:
customers_clean = customers_clean.copy()

print("Copy created successfully.")

Copy created successfully.

In [12]:
customers_clean["first_name"] = (customers_clean["first_name"].str.replace(r"[^a-z]", " ", regex=True))

customers_clean["last_name"] = (customers_clean["last_name"].str.replace(r"[^a-z]", " ", regex=True))

print(customers_clean[["first_name", "last_name"]].head(10))

  first_name last_name
0      maria       day
1   kkeevvin     cantu
2     ronald    daniel
3  katherine     smith
4    brandon    glover
5       toni        li
6    barbara      luna
7    richard    benson
8      james       ali
9        jay  jjoonnes

In [13]:
date_columns = ["dob", "signup_date"]
for col in date_columns:
    customers_clean[col] = pd.to_datetime(customers_clean[col], errors="coerce")
print(customers_clean[date_columns].dtypes)

dob            datetime64[ns]
signup_date    datetime64[ns]
dtype: object

In [14]:
print(customers_clean.isnull().sum())

customer_id        0
first_name         0
last_name          0
email           1018
phone_number       0
gender             0
dob                0
signup_date        0
address            0
city               0
state              0
country            0
device_id(s)       0
source             0
dtype: int64

In [15]:
customers_clean["email"] = (customers_clean["email"].str.strip().str.lower())
print(customers_clean["email"].head(10))

0         maria.day697@hotmail.com
1         kevin.cantu968@gmail.com
2       ronald.daniel138@yahoo.com
3     katherine.smith357@yahoo.com
4    brandon.glover804@hotmail.com
5             toni.li092@gmail.com
6        barbara.luna614@yahoo.com
7      richard.benson220@yahoo.com
8           james.ali627@yahoo.com
9           jay.jones624@yahoo.com
Name: email, dtype: object

In [16]:
customers_clean["phone_number"] = (customers_clean["phone_number"].str.strip())
print(customers_clean["phone_number"].head(10))

0         449.977.1729x282
1       501.347.4824x64633
2    +1-268-822-6332x26814
3             864-894-1347
4             489.732.5436
5            (522)382-8559
6    001-063-045-0948x4636
7             755.281.0372
8               1974876994
9          +1-894-933-6997
Name: phone_number, dtype: object

In [17]:
customers_clean["gender"] = (customers_clean["gender"].str.strip().str.lower())
print(customers_clean["gender"].value_counts())

gender
f    22851
m    22426
o     3702
Name: count, dtype: int64

In [18]:
text_columns = ["address", "city", "state", "country", "device_id(s)", "source"]
for col in text_columns:
    customers_clean[col] = (customers_clean[col].str.strip().str.lower())
print(customers_clean[col].head())

0    referral
1    referral
2         web
3         web
4    referral
Name: source, dtype: object

In [19]:
print(customers_clean.dtypes)

customer_id             object
first_name              object
last_name               object
email                   object
phone_number            object
gender                  object
dob             datetime64[ns]
signup_date     datetime64[ns]
address                 object
city                    object
state                   object
country                 object
device_id(s)            object
source                  object
dtype: object

In [20]:
duplicate_ids = customers_clean["customer_id"].duplicated(keep=False)
print("Rows with duplicate customer ids: ", duplicate_ids.sum())
print("Unique duplicate customer ids:", customers_clean.loc[duplicate_ids, "customer_id"].nunique())

Rows with duplicate customer ids:  1547
Unique duplicate customer ids: 768

In [21]:
customers_clean.to_csv("../01_Raw_Data/customers_clean_checkpoint.csv",index=False)
print("Customer cleaning checkpoint saved.")

Customer cleaning checkpoint saved.

In [22]:
orders_clean = orders.copy()
print(orders_clean.shape)
print(orders_clean.head())

(300000, 8)
                               order_id                           customer_id  \
0  06b5aa88-f86f-4e07-8e4b-6df36402c209  0a331d4c-a73d-4271-83ac-2f6726635495
1  5b10b856-e084-471c-bc16-8dbab95e3f33  9e48263f-7923-4cb9-8138-b9da8eb85619
2  88706122-160e-4721-b537-73cee232fcd5  245fac1f-5ac1-4448-acc9-70ff980a4e9b
3  c6ae75af-0313-4194-a788-8802515af2e4  abfda25e-6a38-4aa8-be24-cd22f371b2b0
4  032ab1c7-8882-47d8-a2ac-fbefc1cfb2eb  e0010492-b072-4f48-abd6-8a87938fad24

  product_id order_amount  order_date payment_method    status quantity
0  PROD-0060       473.82  2025-07-29        wall-et   success        1
1  PROD-0393     17796.32  2024/31/01           card   success        1
2  PROD-0332     31201.75  2024-03-02         wallet   success        2
3  PROD-0059     42282.89         NaN         wallet  refunded        2
4  PROD-0342     27100.3   2024-02-11         wallet   success        1

In [23]:
orders_clean = orders_clean.drop_duplicates()
print("Rows after removing exact duplicates : ", len(orders_clean))

Rows after removing exact duplicates :  300000

In [24]:
orders_clean["order_amount"] = (orders_clean["order_amount"].astype(str).str.replace(",", "", regex=False))
orders_clean["order_amount"] = pd.to_numeric(orders_clean["order_amount"], errors="coerce")
print(orders_clean["order_amount"].dtype)
print(orders_clean["order_amount"].head(10))

float64
0      473.82
1    17796.32
2    31201.75
3    42282.89
4    27100.30
5     2393.67
6    12532.69
7    47079.63
8    32901.99
9     3858.55
Name: order_amount, dtype: float64

In [25]:
orders_clean["order_date"] = pd.to_datetime(orders_clean["order_date"], errors="coerce")
print(orders_clean["order_date"].dtype)
print(orders_clean["order_date"].head(10))

datetime64[ns]
0   2025-07-29
1          NaT
2   2024-03-02
3          NaT
4   2024-02-11
5   2025-11-09
6   2025-12-01
7   2025-08-20
8   2025-02-27
9   2023-12-30
Name: order_date, dtype: datetime64[ns]

In [26]:
orders_clean["payment_method"] = (orders_clean["payment_method"].str.strip().str.lower())
print(orders_clean["payment_method"].value_counts(dropna=False))

payment_method
upi        77569
wallet     67060
cash       56446
card       56174
crad       10850
c@rd       10684
wall-et    10631
cd         10586
Name: count, dtype: int64

In [27]:
payment_map = {"crad" : "card", "c@rd" : "card", "wall-et" : "wallet", "cd" : "card"}
orders_clean["payment_method"] = (orders_clean["payment_method"].replace(payment_map))
print(orders_clean["payment_method"].value_counts(dropna=False))

payment_method
card      88294
wallet    77691
upi       77569
cash      56446
Name: count, dtype: int64

In [28]:
orders_clean["status"] = (orders_clean["status"].str.strip().str.lower())
print(orders_clean["status"].value_counts(dropna=False))

status
success     208406
refunded     29926
failed       23133
ref          12901
suc          12874
fail         12760
Name: count, dtype: int64

In [29]:
status_map = {"ref" : "refunded", "suc" : "success", "fail" : "failed"}
orders_clean["status"] = (orders_clean["status"].replace(status_map))
print(orders_clean["status"].value_counts(dropna=False))

status
success     221280
refunded     42827
failed       35893
Name: count, dtype: int64

In [30]:
orders_clean["quantity"] = pd.to_numeric(orders_clean["quantity"], errors="coerce")
orders_clean["quantity"] = orders_clean["quantity"].astype("Int64")
print(orders_clean["quantity"].dtype)
print(orders_clean["quantity"].value_counts(dropna=False).sort_index())

Int64
quantity
-3      14939
0       14878
1       44765
2       60270
3       45296
4       45058
5       44647
<NA>    30147
Name: count, dtype: Int64

In [31]:
orders_clean.loc[orders_clean["quantity"] <= 0, "quantity"] = pd.NA
print(orders_clean["quantity"].value_counts(dropna=False).sort_index())

quantity
1       44765
2       60270
3       45296
4       45058
5       44647
<NA>    59964
Name: count, dtype: Int64

In [32]:
orders_clean.loc[orders_clean["order_amount"] <=0, "order_amount"] = np.nan
print(orders_clean["order_amount"].isna().sum())
print(orders_clean["order_amount"].describe())

38628
count    261372.000000
mean      49900.714678
std      128944.531555
min         100.010000
25%       11237.387500
50%       25060.805000
75%       38913.442500
max      999969.870000
Name: order_amount, dtype: float64

In [33]:
print(orders_clean.dtypes)

order_id                  object
customer_id               object
product_id                object
order_amount             float64
order_date        datetime64[ns]
payment_method            object
status                    object
quantity                   Int64
dtype: object

In [34]:
print(orders_clean.isnull().sum())

order_id              0
customer_id           0
product_id            0
order_amount      38628
order_date        90000
payment_method        0
status                0
quantity          59964
dtype: int64

In [35]:
orders_clean.to_csv("../01_Raw_Data/orders_clean_checkpoint.csv",index=False)
print("Orders cleaning checkpoint saved.")

Orders cleaning checkpoint saved.

In [36]:
support_clean = support.copy()
print(support_clean.shape)
print(support_clean.head())

(30000, 8)
                              ticket_id                           customer_id  \
0  b88e879e-d3c6-41ae-9aa3-140a5512936c  0c27206e-a220-474b-83fa-3017bae1a8c8
1  036df0e5-42e2-47f8-be4f-9cab16b4174f  e7ba0466-bdf5-47dc-bd21-0a87d1bb7ffe
2  b6fcfc41-e045-4f79-8447-5a1464741d76  a2bd0e7f-a1a2-49a2-9b0f-32b06207f3ab
3  2394323b-cea4-401f-b11e-206bb609d17f  ea0320ec-675d-42be-bcf8-ec2b2a71b14b
4  bc2183e9-c0c1-4d33-b738-ab3ec7ba4455  c79c0aa3-659e-4b0a-9b99-77a93e302bea

  issue_type       ticket_created      ticket_resolved  resolution_time_hours  \
0    payment                  NaN  2024-06-19T07:27:03                  166.0
1    payment                  NaN  2025-07-16T07:34:31                   96.0
2    payment  2024-01-08T10:13:06  2025-12-12T28:77:10                   98.0
3    payment  2024-06-17T07:37:37  2024-06-25T12:37:37                  197.0
4      delay  2025-12-12T28:77:10  2025-08-18T19:03:58                   13.0

  sentiment     support_agent
0   neutral   Felicia Rodgers
1   neutral       Robert Ball
2   neutral      Kaathy Berry
3  positive      Julie Bishop
4  NEGATIVE    Margaret Morse

In [37]:
support_clean = support_clean.drop_duplicates()
print("Rows after removing exact duplicate values is: ", len(support_clean))

Rows after removing exact duplicate values is:  30000

In [38]:
text_columns = ["issue_type", "sentiment", "support_agent"]
for col in text_columns:
    support_clean[col] = support_clean[col].str.strip().str.lower()
print(support_clean[text_columns].head())

  issue_type sentiment    support_agent
0    payment   neutral  felicia rodgers
1    payment   neutral      robert ball
2    payment   neutral     kaathy berry
3    payment  positive     julie bishop
4      delay  negative   margaret morse

In [39]:
for col in ["ticket_created", "ticket_resolved"]:
    support_clean[col] = pd.to_datetime(support_clean[col], errors="coerce")
print(support_clean[["ticket_created","ticket_resolved"]].dtypes)

ticket_created     datetime64[ns]
ticket_resolved    datetime64[ns]
dtype: object

In [40]:
print(support_clean["sentiment"].value_counts(dropna=False))

sentiment
positive    8183
negative    8176
neutral     8071
neu         1509
neg         1497
pos         1474
n3utral      387
positiv3     357
n3gativ3     346
Name: count, dtype: int64

In [41]:
sentiment_map = {"neu" : "neutral", "neg" : "negative", "pos" : "positive", "n3utral" : "neutral", "positiv3" : "positive", "n3gativ3" : "negative"}
support_clean["sentiment"] = support_clean["sentiment"].replace(sentiment_map)
print(support_clean["sentiment"].value_counts(dropna=False))

sentiment
negative    10019
positive    10014
neutral      9967
Name: count, dtype: int64

In [42]:
print(support_clean["issue_type"].value_counts(dropna=False))

issue_type
product     6414
delay       6095
refund      6093
payment     6030
r3fund       323
pro          306
tnemyap      306
refund_      302
delayx       294
dnufer       294
paymentx     289
delay_       284
pay          282
refundx      280
ref          280
paym3nt      279
payment_     278
productx     276
tcudorp      274
product_     272
d3lay        255
yaled        253
del          241
Name: count, dtype: int64

In [43]:
issue_type_map = {"r3fund" : "refund", "pro" : "product", "tnemyap" : "payment", "refund_" : "refund", "delayx" : "delay", "dnufer" : "refund", "paymentx" : "payment", "delay_" : "delay", "pay" : "payment", "refundx" : "refund", "ref" : "refund", "paym3nt" : "payment", "payment_" : "payment", "productx" : "product", "tcudorp" : "product", "product_" : "product", "d3lay" : "delay", "yaled" : "delay", "del" : "delay"}
support_clean["issue_type"] = support_clean["issue_type"].replace(issue_type_map)
print(support_clean["issue_type"].value_counts(dropna=False))

issue_type
refund     7572
product    7542
payment    7464
delay      7422
Name: count, dtype: int64

In [44]:
print(support_clean["resolution_time_hours"].describe())

count    30000.000000
mean       121.008733
std         69.095965
min          1.000000
25%         62.000000
50%        121.000000
75%        181.000000
max        240.000000
Name: resolution_time_hours, dtype: float64

In [45]:
print(support_clean.isna().sum())

ticket_id                   0
customer_id                 0
issue_type                  0
ticket_created           9000
ticket_resolved          9000
resolution_time_hours       0
sentiment                   0
support_agent               0
dtype: int64

In [46]:
support_clean.to_csv("../01_Raw_Data/support_clean_checkpoint.csv",index=False)
print("Support cleaning checkpoint saved.")

Support cleaning checkpoint saved.

In [47]:
products_clean = products.copy()
print(products_clean.shape)
print(products_clean.head())

(500, 4)
  product_id        product_name     category      price
0  PROD-0001     Open Beaautiful          clo   32309.95
1  PROD-0002          Race Third   automotive   47346.82
2  PROD-0003           MEAN YOUR  3l3ctronics       -100
3  PROD-0004  Consumer Newspaper         toys   28506.95
4  PROD-0005               A Hot     clothing   19165.58

In [48]:
products_clean = products_clean.drop_duplicates()
print("Rows after removing exact duplicate is: ", len(products_clean))

Rows after removing exact duplicate is:  500

In [49]:
products_clean["product_name"] = products_clean["product_name"].str.strip().str.lower()
products_clean["category"] = products_clean["category"].str.strip().str.lower()
print(products_clean[["product_name", "category"]].head())

         product_name     category
0     open beaautiful          clo
1          race third   automotive
2           mean your  3l3ctronics
3  consumer newspaper         toys
4               a hot     clothing

In [50]:
print(products_clean["category"].value_counts(dropna=False))

category
clothing        60
kitchen         59
sports          51
toys            51
beauty          50
automotive      47
home            46
electronics     44
NaN             30
3l3ctronics      8
hom3             5
hom              5
bea              4
clo              4
kit              4
kitch3n          4
clothing-        3
automotiv3       3
b3auty           3
ele              3
electronics_     2
clothing_        2
beauty_          2
home_            2
aut              1
automotive_      1
kitchen-         1
toy              1
toys-            1
home-            1
sports-          1
beauty-          1
Name: count, dtype: int64

In [51]:
category_map = {
    "3l3ctronics": "electronics",
    "ele": "electronics",
    "electronics_": "electronics",
    "hom3": "home",
    "hom": "home",
    "home_": "home",
    "home-": "home",
    "bea": "beauty",
    "b3auty": "beauty",
    "beauty_": "beauty",
    "beauty-": "beauty",
    "clo": "clothing",
    "clothing_": "clothing",
    "clothing-": "clothing",
    "kit": "kitchen",
    "kitch3n": "kitchen",
    "kitchen-": "kitchen",
    "automotiv3": "automotive",
    "automotive_": "automotive",
    "aut": "automotive",
    "toy": "toys",
    "toys-": "toys",
    "electronics_": "electronics"
}

products_clean["category"] = products_clean["category"].replace(category_map)

print(products_clean["category"].value_counts(dropna=False))

category
clothing       69
kitchen        68
beauty         60
home           59
electronics    57
toys           53
automotive     52
sports         51
NaN            30
sports-         1
Name: count, dtype: int64

In [52]:
products_clean["category"] = products_clean["category"].replace({"sports-" : "sports"})
print(products_clean["category"].value_counts(dropna=False))

category
clothing       69
kitchen        68
beauty         60
home           59
electronics    57
toys           53
automotive     52
sports         52
NaN            30
Name: count, dtype: int64

In [53]:
products_clean["price"] = (products_clean["price"].astype(str).str.replace(",", "", regex=False))
products_clean["price"] = pd.to_numeric(products_clean["price"], errors="coerce")
print(products_clean["price"].dtypes)

float64

In [54]:
products_clean.loc[products_clean["price"] <= 0, "price"] = np.nan
print(products_clean["price"].isna().sum())

71

In [55]:
print(products_clean.isna().sum())

product_id       0
product_name     0
category        30
price           71
dtype: int64

In [56]:
products_clean.to_csv("../01_Raw_Data/products_clean_checkpoint.csv",index=False)
print("Products cleaning checkpoint saved.")

Products cleaning checkpoint saved.

In [57]:
clickstream_clean = clickstream.copy()
print(clickstream_clean.shape)
print(clickstream_clean.head())

(500000, 8)
                               event_id                            session_id  \
0  aa56e7fb-5d80-4807-86dc-1f742f655fbe  8ee809b4-5d5b-4fed-99c6-67a74e8fe3e9
1  9ea31e17-ffce-4d2b-93f2-979fafac5b9b  9efcf371-ae3b-4a9e-956b-67dbc09935c0
2  dadd5a4b-3654-440d-adb1-b7a3ff181da3  51d6406d-abd3-4f96-8fe9-039088694420
3  c0f6a7b0-f688-4aac-8740-11821f7f086e  41a4433e-fcf4-4f20-8264-ddbdd0bfb567
4  e0cc5a38-1047-4d47-9679-7238b3ff9e79  ec4f96c4-82c5-4622-bbba-961efa314a9a

                            customer_id event_type  \
0                                   NaN      login
1  ea0320ec-675d-42be-bcf8-ec2b2a71b14b  page_view
2  5160a713-dde1-404a-8b29-f3cc1192a694      login
3  d8fde909-fe69-4f34-9290-cebfc268c31c     search
4  fc905a7d-b0b4-4217-ad84-c300dbfdeac9  page_view

                                     page_url  \
0     https://shop.example.com/search?q=shoes
1  https://shop.example.com/product/PROD-0109
2                   https://shop.example.com/
3                   https://shop.example.com/
4  https://shop.example.com/product/PROD-0143

                              device_id                         timestamp  \
0  9a921b19-37df-4ed4-85d0-8583864f8d1d  2025-09-26T16:03:31.922468+00:00
1  06e4844b-068b-41f4-9c78-120424a84b72  2025-10-15T12:27:28.922583+00:00
2  8bcca371-31ce-4420-801f-6b18a7512463  2025-09-03T07:46:34.922628+00:00
3  f0241556-af81-429b-ab06-e19a4ec37f2b               2024/31/01 25:61:00
4  6dd78212-572a-41c4-88e8-deded58c3bb6  2025-10-06T19:03:15.922725+00:00

                          ingest_run_id
0  920fe448-95d0-4ccb-b77b-2c7cfa389054
1  920fe448-95d0-4ccb-b77b-2c7cfa389054
2  920fe448-95d0-4ccb-b77b-2c7cfa389054
3  920fe448-95d0-4ccb-b77b-2c7cfa389054
4  920fe448-95d0-4ccb-b77b-2c7cfa389054

In [58]:
clickstream_clean = clickstream_clean.drop_duplicates()
print("Rows after removing exact duplicates is: ", len(clickstream_clean))

Rows after removing exact duplicates is:  500000

In [59]:
text_columns = ["event_id", "session_id", "customer_id", "event_type", "page_url", "device_id", "ingest_run_id"]
for col in text_columns:
    clickstream_clean[col] = clickstream_clean[col].astype(str).str.strip().str.lower()
print(clickstream_clean.dtypes)

event_id         object
session_id       object
customer_id      object
event_type       object
page_url         object
device_id        object
timestamp        object
ingest_run_id    object
dtype: object

In [60]:
clickstream_clean["timestamp"] = pd.to_datetime(clickstream_clean["timestamp"], errors="coerce")
print(clickstream_clean["timestamp"].dtype)
print("Missing/invalid timestamps :", clickstream_clean["timestamp"].isna().sum())

datetime64[ns, UTC]
Missing/invalid timestamps : 80237

In [61]:
print(clickstream_clean.isna().sum())

event_id             0
session_id           0
customer_id          0
event_type           0
page_url             0
device_id            0
timestamp        80237
ingest_run_id        0
dtype: int64

In [62]:
clickstream_clean.to_csv("../01_Raw_Data/clickstream_clean_checkpoint.csv",index=False)
print("Clickstream cleaning checkpoint saved.")

Clickstream cleaning checkpoint saved.

In [63]:
checkpoint_files = [
    "customers_clean_checkpoint.csv",
    "orders_clean_checkpoint.csv",
    "support_clean_checkpoint.csv",
    "products_clean_checkpoint.csv",
    "clickstream_clean_checkpoint.csv"
]

for file in checkpoint_files:
    path = f"../01_Raw_Data/{file}"
    print(file, "→", "Found" if os.path.exists(path) else "Missing")

customers_clean_checkpoint.csv → Found
orders_clean_checkpoint.csv → Found
support_clean_checkpoint.csv → Found
products_clean_checkpoint.csv → Found
clickstream_clean_checkpoint.csv → Found

In [64]:
customers_clean = pd.read_csv(r"D:\Customer_360\01_Raw_Data\customers_clean_checkpoint.csv")
orders_clean = pd.read_csv(r"D:\Customer_360\01_Raw_Data\orders_clean_checkpoint.csv")
support_clean = pd.read_csv(r"D:\Customer_360\01_Raw_Data\support_clean_checkpoint.csv")
products_clean = pd.read_csv(r"D:\Customer_360\01_Raw_Data\products_clean_checkpoint.csv")
clickstream_clean = pd.read_csv(r"D:\Customer_360\01_Raw_Data\clickstream_clean_checkpoint.csv")
print("All cleaned datasets loaded successfully")

All cleaned datasets loaded successfully

In [65]:
print("Customers: ", customers_clean.shape)
print("Orders: ", orders_clean.shape)
print("Support: ", support_clean.shape)
print("Products: ", products_clean.shape)
print("Clickstream: ", clickstream_clean.shape)

Customers:  (48979, 14)
Orders:  (300000, 8)
Support:  (30000, 8)
Products:  (500, 4)
Clickstream:  (500000, 8)

In [66]:
print("Customers")
print(customers_clean.dtypes)
print("\nOrders:")
print(orders_clean.dtypes)
print("\nSupport:")
print(support_clean.dtypes)
print("\nProducts:")
print(products_clean.dtypes)
print("\nClickstream:")
print(clickstream_clean.dtypes)

Customers
customer_id     object
first_name      object
last_name       object
email           object
phone_number    object
gender          object
dob             object
signup_date     object
address         object
city            object
state           object
country         object
device_id(s)    object
source          object
dtype: object

Orders:
order_id           object
customer_id        object
product_id         object
order_amount      float64
order_date         object
payment_method     object
status             object
quantity          float64
dtype: object

Support:
ticket_id                 object
customer_id               object
issue_type                object
ticket_created            object
ticket_resolved           object
resolution_time_hours    float64
sentiment                 object
support_agent             object
dtype: object

Products:
product_id       object
product_name     object
category         object
price           float64
dtype: object

Clickstream:
event_id         object
session_id       object
customer_id      object
event_type       object
page_url         object
device_id        object
timestamp        object
ingest_run_id    object
dtype: object

In [67]:
# Customers
customers_clean["dob"] = pd.to_datetime(
    customers_clean["dob"], errors="coerce"
)
customers_clean["signup_date"] = pd.to_datetime(
    customers_clean["signup_date"], errors="coerce"
)

# Orders
orders_clean["order_date"] = pd.to_datetime(
    orders_clean["order_date"], errors="coerce"
)

# Support
support_clean["ticket_created"] = pd.to_datetime(
    support_clean["ticket_created"], errors="coerce"
)
support_clean["ticket_resolved"] = pd.to_datetime(
    support_clean["ticket_resolved"], errors="coerce"
)

# Clickstream
clickstream_clean["timestamp"] = pd.to_datetime(
    clickstream_clean["timestamp"], errors="coerce"
)

print("Date/time columns converted successfully.")

Date/time columns converted successfully.

In [68]:
print("Customers:", customers_clean[["dob", "signup_date"]].dtypes)
print("Orders:", orders_clean["order_date"].dtype)
print("Support:", support_clean[["ticket_created", "ticket_resolved"]].dtypes)
print("Clickstream:", clickstream_clean["timestamp"].dtype)

Customers: dob            datetime64[ns]
signup_date    datetime64[ns]
dtype: object
Orders: datetime64[ns]
Support: ticket_created     datetime64[ns]
ticket_resolved    datetime64[ns]
dtype: object
Clickstream: datetime64[ns, UTC]

In [69]:
print("CUSTOMERS")
print(customers_clean.isna().sum())

print("\nORDERS")
print(orders_clean.isna().sum())

print("\nSUPPORT")
print(support_clean.isna().sum())

print("\nPRODUCTS")
print(products_clean.isna().sum())

print("\nCLICKSTREAM")
print(clickstream_clean.isna().sum())

CUSTOMERS
customer_id        0
first_name         0
last_name          0
email           1018
phone_number       0
gender             0
dob                0
signup_date        0
address            0
city               0
state              0
country            0
device_id(s)       0
source             0
dtype: int64

ORDERS
order_id              0
customer_id           0
product_id            0
order_amount      38628
order_date        90000
payment_method        0
status                0
quantity          59964
dtype: int64

SUPPORT
ticket_id                   0
customer_id                 0
issue_type                  0
ticket_created           9000
ticket_resolved          9000
resolution_time_hours       0
sentiment                   0
support_agent               0
dtype: int64

PRODUCTS
product_id       0
product_name     0
category        30
price           71
dtype: int64

CLICKSTREAM
event_id              0
session_id            0
customer_id      150553
event_type            0
page_url           8305
device_id             0
timestamp         80237
ingest_run_id         0
dtype: int64

In [70]:
print(
    "Orders → Customers invalid:",
    (~orders_clean["customer_id"].isin(customers_clean["customer_id"])).sum()
)

print(
    "Orders → Products invalid:",
    (~orders_clean["product_id"].isin(products_clean["product_id"])).sum()
)

print(
    "Support → Customers invalid:",
    (~support_clean["customer_id"].isin(customers_clean["customer_id"])).sum()
)

# Exclude missing customer IDs from Clickstream
click_customer_check = clickstream_clean["customer_id"].dropna()

print(
    "Clickstream → Customers invalid:",
    (~click_customer_check.isin(customers_clean["customer_id"])).sum()
)

Orders → Customers invalid: 0
Orders → Products invalid: 0
Support → Customers invalid: 0
Clickstream → Customers invalid: 0

In [71]:
print(
    "Orders with invalid amount:",
    (orders_clean["order_amount"] <= 0).sum()
)

print(
    "Orders with invalid quantity:",
    (orders_clean["quantity"] <= 0).sum()
)

print(
    "Products with invalid price:",
    (products_clean["price"] <= 0).sum()
)

print(
    "Support with invalid resolution time:",
    (support_clean["resolution_time_hours"] < 0).sum()
)

Orders with invalid amount: 0
Orders with invalid quantity: 0
Products with invalid price: 0
Support with invalid resolution time: 0

In [72]:
customers_clean.to_csv("../01_Raw_Data/customers_clean.csv", index=False)
orders_clean.to_csv("../01_Raw_Data/orders_clean.csv", index=False)
support_clean.to_csv("../01_Raw_Data/support_clean.csv", index=False)
products_clean.to_csv("../01_Raw_Data/products_clean.csv", index=False)
clickstream_clean.to_csv("../01_Raw_Data/clickstream_clean.csv", index=False)

print("Final cleaned datasets saved successfully.")

Final cleaned datasets saved successfully.

In [73]:
print("=== CUSTOMER 360 — PHASE 3 ETL SUMMARY ===")

print("\nFinal dataset sizes:")
print("Customers:", customers_clean.shape)
print("Orders:", orders_clean.shape)
print("Support:", support_clean.shape)
print("Products:", products_clean.shape)
print("Clickstream:", clickstream_clean.shape)

print("\nFinal output files:")
print("customers_clean.csv")
print("orders_clean.csv")
print("support_clean.csv")
print("products_clean.csv")
print("clickstream_clean.csv")

print("\nPhase 3 ETL validation:")
print("✓ Exact duplicates handled")
print("✓ Text standardized")
print("✓ Dates/timestamps standardized")
print("✓ Numeric values cleaned")
print("✓ Categories standardized")
print("✓ Referential integrity validated")
print("✓ Business rules validated")
print("✓ Final cleaned datasets exported")

=== CUSTOMER 360 — PHASE 3 ETL SUMMARY ===

Final dataset sizes:
Customers: (48979, 14)
Orders: (300000, 8)
Support: (30000, 8)
Products: (500, 4)
Clickstream: (500000, 8)

Final output files:
customers_clean.csv
orders_clean.csv
support_clean.csv
products_clean.csv
clickstream_clean.csv

Phase 3 ETL validation:
✓ Exact duplicates handled
✓ Text standardized
✓ Dates/timestamps standardized
✓ Numeric values cleaned
✓ Categories standardized
✓ Referential integrity validated
✓ Business rules validated
✓ Final cleaned datasets exported

In [74]:
df = pd.read_csv(r'D:\Customer_360\01_Raw_Data\products_clean.csv')
df.to_csv('products_mysql.csv', index=False, na_rep='NULL')
print(df.shape)  # should print (500, 4)

(500, 4)

In [75]:
products_mysql = pd.read_csv(r"D:\Customer_360\03_Python_ETL\products_mysql.csv")
print(products_mysql.isna().sum())

product_id       0
product_name     0
category        30
price           71
dtype: int64

In [76]:
pd.read_csv(r"D:\Customer_360\01_Raw_Data\customers_clean.csv").to_csv("customers_mysql.csv", index=False, na_rep='NULL')

In [77]:
pd.read_csv(r"D:\Customer_360\01_Raw_Data\orders_clean.csv").to_csv("orders_mysql.csv", index=False, na_rep='NULL')

In [78]:
pd.read_csv(r"D:\Customer_360\01_Raw_Data\support_clean.csv").to_csv("support_mysql.csv", index=False, na_rep='NULL')

In [79]:
pd.read_csv(r"D:\Customer_360\01_Raw_Data\clickstream_clean.csv").to_csv("clickstream_mysql.csv", index=False, na_rep='NULL')

In [80]:
print(orders_clean["order_amount"].sum())

13042649596.810001